[project]
name = "invest-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "finance-datareader>=0.9.101",
    "plotly>=6.5.0",
    "pykrx>=1.0.51",
    "setuptools>=80.9.0,<81",
    "streamlit>=1.52.2",
]
